version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    container_name: viljami-xyz-web
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "no"
